demo:bigdata.cpp database.h database.cpp
	g++ --std=c++11 -Wall -O3 -o demo database.cpp bigdata.cpp

bigdata:bigdata.cpp database.h database.cpp
	g++ --std=c++11 -Wall -g3 -O3 -o bigdata database.cpp bigdata.cpp 
test:test.cpp
	g++ --std=c++11 -Wall -O3 -o test test.cpp
